site_name: My Docs
site_url: https://ad83.info
theme:
  name: material

extra_javascript:
  - javascripts/toc-toggle.js

extra_css:
  - stylesheets/toc-toggle.css

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
